#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# The redirection must be a “301 Moved Permanently”

old_line="\tserver_name _;"
new_line="\tserver_name _;\n\tlocation /redirect_me {\n\t\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sed -i "s/$old_line/$new_line/" /etc/nginx/sites-enabled/default
service nginx reload