#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# The redirection must be a “301 Moved Permanently”

old_line="\tserver_name _;"
new_line="\tserver_name _;\n\n\tlocation \/redirect_me {\n\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n\n\terror_page 404 \/404.html;\n\n\tlocation = \/404.html {\n\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}\n"
sed -i "s/$old_line/$new_line/" default
