#!/usr/bin/env bash
# configures a new Ubuntu machine to respect the following requirements :
#	install haproxy
#	configure it to send traffic to web-01 and web-02 using a roundrobin algorithm

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update -y
sudo apt-get install -y haproxy=1.8.*

echo "
frontend localnodes
	bind *:80
	mode http
	default_backend web_back

backend web_back
	mode http
	balance roundrobin
	server 446922-web-01 100.25.170.65:80 check
	server 446922-web-02 54.172.165.136:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
