#!/usr/bin/env bash
# configures a new Ubuntu machine to respect the following requirements :
#	install haproxy
#	configure it to send traffic to web-01 and web-02 using a roundrobin algorithm

apt-get update
apt-get install -y haproxy=2.0.\*
echo "
listen web_servers
	bind *:80
	mode http
	balance roundrobin
	server 446922-web-01 100.25.170.65:80 check
	server 446922-web-02 54.172.165.136:80 check
" >> /etc/haproxy/haproxy.cfg
echo 'ENABLED=1
' >> /etc/default/haproxy
service haproxy restart
