#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it.

mysqldump --all-databases -u root -p "$1" > backup.sql
mydate=$(date +%d-%m-%Y)
tar -cvf "$mydate.tar.gz" backup.sql
