#!/usr/bin/env bash
# a Bash script that:
#	- Creates the file /var/run/myscript.pid containing its PID
#	- Displays To infinity and beyond indefinitely
#	- Displays I hate the kill command when receiving a SIGTERM signal
#	- Displays Y U no love me?! when receiving a SIGINT signal
#	- Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

mypid=$$

handle_SIGTERM () {
	echo "I hate the kill command"
	rm /var/run/myscript.pid
	exit 1
}

handle_SIGINT () {
	echo "Y U no love me?!"
	exit 1
}

handle_SIGQUIT () {
	rm /var/run/myscript.pid
	exit 1
}

trap handle_SIGTERM SIGTERM
trap handle_SIGINT SIGINT
trap handle_SIGQUIT SIGQUIT

echo "$mypid" > /var/run/myscript.pid

while true
do
	echo 'To infinity and beyond'
	sleep 2
done