#!/usr/bin/env bash
# a Bash script that gives you information about the school file.

for ((i=1;i<=100;i+=1))
do

	if [ $(( i % 15 )) = 0 ]
	then
		echo "FizzBuzz"
	elif [ "$(( i % 3 ))" = 0 ]
	then
		echo "Fizz"
	elif [ "$(( i % 5 ))" = 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi

done