#!/usr/bin/env bash
# a Bash script that gives you information about the school file.

school="./school"
if [ -e $school ]
then
	echo "school file exists"

	if [ -s $school ]
	then
		echo "school file is not empty"

		if ! [ -d $school ]
		then
			echo "school is a regular file"
		fi
	else
		echo "school file is empty"
	fi

else
	echo "school file does not exists"
fi