#!/usr/bin/env bash
# This script changes the IP address of the localhost and facebook.com

sed -i 's/127\.0\.0\.1\tlocalhost/127\.0\.0\.2\tlocalhost' /etc/hosts
echo "8.8.8.8	facebook.com" >> /etc/hosts
