#!/usr/bin/env bash
# This script changes the IP address of the localhost and facebook.com

sed -i '/\tlocalhost/d' /etc/hosts
echo "127.0.0.2	localhost" >> /etc/hosts
echo "8.8.8.8	facebook.com" >> /etc/hosts
