#!/usr/bin/env bash
# This script reloads gunicorn in graceful way

# Get the pid of the gunicorn process

pid=$(ps aux | grep -m 1'gunicorn' | awk '{print $2}')

# Send HUP signal to the process

sudo kill -HUP "$pid"
